# Generated by Django 4.1.10 on 2023-08-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_profile',
            name='turf_price',
            field=models.IntegerField(default=9999991),
        ),
        migrations.CreateModel(
            name='Turf_index_profile',
            fields=[
                ('turf_id', models.AutoField(primary_key=True, serialize=False)),
                ('turf_name', models.CharField(default='', max_length=100)),
                ('turf_address', models.CharField(default='Please enter the address owner', max_length=200)),
                ('turf_rating', models.IntegerField(default=0, max_length=1)),
                ('turf_price', models.IntegerField(default=9999991)),
                ('turf_picture', models.ImageField(upload_to='BookTurf/BookTurfMain/media/BookTurfMain')),
                ('turf_new_profile', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='BookTurfMain.turf_profile')),
            ],
        ),
    ]
