# Generated by Django 4.1.10 on 2023-08-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0002_turf_profile_turf_price_turf_index_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_image',
        ),
        migrations.AddField(
            model_name='turf_pics',
            name='turf_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookTurfMain.turf_profile'),
        ),
        migrations.DeleteModel(
            name='Turf_index_profile',
        ),
    ]
