# Generated by Django 4.1.10 on 2023-08-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0003_remove_turf_profile_turf_image_turf_pics_turf_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_pics',
            name='turf_ref',
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookTurfMain.turf_pics'),
        ),
        migrations.AlterField(
            model_name='turf_pics',
            name='turf_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
