# Generated by Django 4.1.10 on 2023-08-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0004_remove_turf_pics_turf_ref_turf_profile_turf_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_ref',
        ),
        migrations.AddField(
            model_name='turf_pics',
            name='turf_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookTurfMain.turf_profile'),
        ),
    ]
