# Generated by Django 4.1.10 on 2023-08-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0005_remove_turf_profile_turf_ref_turf_pics_turf_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_profile',
            name='turf_ownerContact_number',
            field=models.BigIntegerField(default=9999999991),
        ),
        migrations.AlterField(
            model_name='turf_profile',
            name='turf_rating',
            field=models.IntegerField(default=0),
        ),
    ]
