# Generated by Django 4.1.10 on 2023-08-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0006_alter_turf_profile_turf_ownercontact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_category',
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_category',
            field=models.ManyToManyField(blank=True, choices=[('option1', 'Football'), ('option2', 'Parking'), ('option3', '12+ players'), ('option3', '8+ players'), ('custom', 'CustoM')], to='BookTurfMain.turf_profile'),
        ),
    ]
