# Generated by Django 4.1.10 on 2023-08-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0008_remove_turf_profile_turf_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_profile',
            name='turf_category_1',
            field=models.ManyToManyField(blank=True, choices=[('option1', 'Football'), ('option2', 'Parking'), ('option3', '12+ players'), ('option3', '8+ players')], default=None, to='BookTurfMain.turf_profile'),
        ),
    ]
