# Generated by Django 4.1.10 on 2023-09-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0012_alter_turf_profile_turf_category_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_profile',
            name='turf_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
