# Generated by Django 4.1.10 on 2023-09-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0013_alter_turf_profile_turf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_profile',
            name='turf_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
