# Generated by Django 4.1.10 on 2023-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0015_addmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_category_1',
        ),
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_category_2',
        ),
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_category_3',
        ),
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_category_4',
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_category_1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_category_2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_category_3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_category_4',
            field=models.CharField(default='', max_length=300),
        ),
    ]
