# Generated by Django 4.1.10 on 2023-09-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0016_remove_turf_profile_turf_category_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_profile',
            name='turf_host_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_map',
            field=models.CharField(default='', max_length=300),
        ),
    ]
