# Generated by Django 4.1.10 on 2023-09-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0017_turf_profile_turf_host_name_turf_profile_turf_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_reviews',
        ),
    ]
