# Generated by Django 4.2.4 on 2023-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0018_remove_turf_profile_turf_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_profile',
            name='turf_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
