# Generated by Django 4.1.10 on 2023-09-25 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookTurfMain', '0019_alter_turf_profile_turf_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_profile',
            name='turf_friday_base',
            field=models.IntegerField(default=9999999),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_friday_peak',
            field=models.IntegerField(default=9999999),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_saturday_base',
            field=models.IntegerField(default=9999999),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_saturday_peak',
            field=models.IntegerField(default=9999999),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_sunday_base',
            field=models.IntegerField(default=9999999),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_sunday_peak',
            field=models.IntegerField(default=9999999),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_weekday_base',
            field=models.IntegerField(default=9999999),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_weekday_peak',
            field=models.IntegerField(default=9999999),
        ),
        migrations.CreateModel(
            name='Turf_Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_price', models.IntegerField(default=999999999)),
                ('turf_timeslot', models.CharField(default='timeslot...', max_length=200)),
                ('turf_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookTurfMain.turf_profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
