# Generated by Django 4.1.10 on 2023-09-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0020_turf_profile_turf_friday_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_booked',
            name='turf_field_booked',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_field_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_field_2',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_field_3',
            field=models.IntegerField(default=3),
        ),
    ]
