# Generated by Django 4.2.4 on 2023-09-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0021_turf_booked_turf_field_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_profile',
            name='custom_timeslot',
            field=models.JSONField(default=['5-6 am', '6-7 am', '7-8 am', '8-9 am', '9-10 am', '10-11 am', '11-12 pm', '12-1 pm', '1-2 pm', '2-3 pm', '3-4 pm', '4-5 pm', '5-6 pm', '6-7 pm', '7-8 pm', '8-9 pm', '9-10 pm', '10-11 pm', '11-12 am', '12-1 am', '1-2 am', '2-3 am', '3-4 am', '4-5 am']),
        ),
    ]
