# Generated by Django 4.2.4 on 2023-09-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0022_turf_profile_custom_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_field_1',
        ),
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_field_2',
        ),
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_field_3',
        ),
    ]
