# Generated by Django 4.2.4 on 2023-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0023_remove_turf_profile_turf_field_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_profile',
            name='turf_field_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_field_2',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='turf_field_3',
            field=models.IntegerField(default=3),
        ),
    ]
