# Generated by Django 4.2.4 on 2023-09-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0024_turf_profile_turf_field_1_turf_profile_turf_field_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_profile',
            name='custom_timeslot',
            field=models.JSONField(default=['12-1 AM', '1-2 AM', '2-3 AM', '3-4 AM', '4-5 AM', '5-6 AM', '6-7 AM', '7-8 AM', '8-9 AM', '9-10 AM', '10-11 AM', '11-12 PM', '12-1 PM', '1-2 PM', '2-3 PM', '3-4 PM', '4-5 PM', '5-6 PM', '6-7 PM', '7-8 PM', '8-9 PM', '9-10 PM', '10-11 PM', '11-12 AM']),
        ),
    ]
