# Generated by Django 4.1.10 on 2023-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0025_alter_turf_profile_custom_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_field_1',
        ),
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_field_2',
        ),
        migrations.RemoveField(
            model_name='turf_profile',
            name='turf_field_3',
        ),
        migrations.AddField(
            model_name='turf_profile',
            name='removed_timeslot',
            field=models.JSONField(default=[]),
        ),
    ]
