# Generated by Django 4.2.4 on 2023-10-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0026_remove_turf_profile_turf_field_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_profile',
            name='peak_timeslot',
            field=models.JSONField(default=[]),
        ),
    ]
