# Generated by Django 4.1.10 on 2023-10-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0027_turf_profile_peak_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_booked',
            name='turf_field_booked',
        ),
        migrations.AddField(
            model_name='turf_booked',
            name='turf_date',
            field=models.CharField(default='datee...', max_length=200),
        ),
        migrations.AlterField(
            model_name='turf_profile',
            name='peak_timeslot',
            field=models.JSONField(default=['12-1 AM', '1-2 AM', '2-3 AM', '3-4 AM', '4-5 AM', '6-7 PM', '7-8 PM', '8-9 PM', '9-10 PM', '10-11 PM', '11-12 AM']),
        ),
    ]
