# Generated by Django 4.1.10 on 2023-10-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0028_remove_turf_booked_turf_field_booked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf_Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username...', max_length=200)),
                ('email', models.CharField(default='email...', max_length=200)),
                ('password', models.CharField(default='password...', max_length=200)),
                ('turf_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookTurfMain.turf_profile')),
            ],
        ),
    ]
