# Generated by Django 4.1.10 on 2023-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTurfMain', '0030_remove_turf_profile_turf_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_booked',
            name='turf_price',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='turf_profile',
            name='turf_price',
            field=models.IntegerField(default=800),
        ),
    ]
